### ISSUE TITLE
[BUG] Concatenation failed

### ISSUE THREAD

**Issue by miladsade96** [EverLookNeverSee/Optimized-U-Net#2]
When we run the code , we get a value error:
![valueError](https://user-images.githubusercontent.com/57490926/140756632-2e109b7a-7d2f-49d3-b59e-5547bc279cb8.png)

**Comment by Himanshu1331** [comment]
how to modify the feature sizes from auxiliary outputs for correctly mapping to a loss function?

**Comment by miladsade96** [comment]
Unfortunately i don't know :)

**Comment by Himanshu1331** [comment]
never mind sir, thank you for responding.

Regards
Himanshu
India
